apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: test-gitea
  namespace: cert-manager
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: gitea
  to:
  - group: ""
    kind: Secret
    name: cert-dubyatp-xyz