apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: weyma-vault
    kind: ClusterSecretStore
  target:
    name: prometheus-auth
    creationPolicy: Owner
  data:
  - secretKey: .basicauthpass
    remoteRef:
      key: monitoring
      property: prometheus-password