apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: weyma-vault
    kind: ClusterSecretStore
  target:
    name: discord-webhook
    creationPolicy: Owner
  data:
  - secretKey: webhook
    remoteRef:
      key: monitoring
      property: discord_webhook