apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: weyma-bm-store
  namespace: rook-ceph
spec:
  auth: {}
  dataPool:
    application: ''
    erasureCoded:
      codingChunks: 1
      dataChunks: 2
    failureDomain: host
    mirroring: {}
    quotas: {}
    replicated:
      size: 0
    statusCheck:
      mirror: {}
  gateway:
    instances: 1
    placement: {}
    port: 80
    resources: {}
  healthCheck: {}
  metadataPool:
    application: ''
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: host
    mirroring: {}
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}