apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weyma-s3-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: weyma-s3
  objectStoreNamespace: rook-ceph