apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: weyma-internal-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://weyma-vault.infra.dubyatp.xyz
    path: pki/sign/weyma-talos-cert-manager
    auth:
      appRole:
        path: approle
        roleId: 3318e272-5857-69d1-8015-2566892eec5c
        secretRef:
          name: vault-approle-secret
          key: secretId