{{- if and .Values.monitoring.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-exporter
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: rook-ceph-exporter
      rook_cluster: {{ .Values.monitoring.cluster_name | default "rook-ceph" }}
  endpoints:
    - port: ceph-exporter-http-metrics
      path: /metrics
      interval: 10s
{{- end }}
