services:
  prometheus:
    image: prom/prometheus:v3.2.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.config.file=/etc/prometheus/web-config.yaml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./web-config.yaml:/etc/prometheus/web-config.yaml
      - prometheus-data:/prometheus
volumes:
  prometheus-data: