apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kubevirt-nad
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "bridge",
    "bridge": "br0",
    "ipam": {
      "type": "dhcp"
    }
   }'