apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network = 10.105.10.0/24
    cluster network = 10.105.2.0/24
    public addr = ""
    cluster addr = ""
